import type { Pet } from '@/lib/types';

export const allPets: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: '2 years',
    ageCategory: 'Young',
    size: 'Large',
    gender: 'Male',
    description: 'Buddy is a super friendly and energetic Golden Retriever who loves to play fetch and go on long walks. He is great with kids and other dogs.',
    personalityTraits: ['Friendly', 'Energetic', 'Playful', 'Loyal'],
    images: ['https://loremflickr.com/800/600/golden,retriever?lock=1', 'https://loremflickr.com/400/300/golden,retriever?lock=2', 'https://loremflickr.com/400/300/golden,retriever?lock=3', 'https://loremflickr.com/400/300/golden,retriever?lock=4'],
  },
  {
    id: '2',
    name: 'Lucy',
    type: 'Cat',
    breed: 'Siamese',
    age: '1 year',
    ageCategory: 'Young',
    size: 'Small',
    gender: 'Female',
    description: 'Lucy is a beautiful and affectionate Siamese cat. She loves to cuddle on the couch and chase laser pointers. A perfect companion for a quiet home.',
    personalityTraits: ['Affectionate', 'Vocal', 'Intelligent', 'Cuddly'],
    images: ['https://loremflickr.com/800/600/siamese,cat?lock=5', 'https://loremflickr.com/400/300/siamese,cat?lock=6', 'https://loremflickr.com/400/300/siamese,cat?lock=7', 'https://loremflickr.com/400/300/siamese,cat?lock=8'],
  },
  {
    id: '3',
    name: 'Max',
    type: 'Dog',
    breed: 'German Shepherd',
    age: '3 years',
    ageCategory: 'Adult',
    size: 'Large',
    gender: 'Male',
    description: 'Max is a loyal and intelligent German Shepherd. He is well-trained and would thrive in a home with an experienced owner who can provide him with plenty of mental and physical stimulation.',
    personalityTraits: ['Loyal', 'Intelligent', 'Protective', 'Active'],
    images: ['https://loremflickr.com/800/600/german,shepherd?lock=9', 'https://loremflickr.com/400/300/german,shepherd?lock=10', 'https://loremflickr.com/400/300/german,shepherd?lock=11', 'https://loremflickr.com/400/300/german,shepherd?lock=12'],
  },
  {
    id: '4',
    name: 'Milo',
    type: 'Cat',
    breed: 'Tabby',
    age: '5 months',
    ageCategory: 'Puppy',
    size: 'Small',
    gender: 'Male',
    description: 'Milo is a playful and curious tabby kitten. He is full of energy and loves to explore. He gets along well with other cats and would be a great addition to any family.',
    personalityTraits: ['Playful', 'Curious', 'Energetic', 'Social'],
    images: ['https://loremflickr.com/800/600/tabby,cat?lock=13', 'https://loremflickr.com/400/300/tabby,cat?lock=14', 'https://loremflickr.com/400/300/tabby,cat?lock=15', 'https://loremflickr.com/400/300/tabby,cat?lock=16'],
  },
   {
    id: '5',
    name: 'Rocky',
    type: 'Dog',
    breed: 'Beagle',
    age: '8 months',
    ageCategory: 'Puppy',
    size: 'Medium',
    gender: 'Male',
    description: 'Rocky is a happy-go-lucky Beagle puppy with a nose for adventure. He loves sniffing around the yard and is very food motivated, making him easy to train.',
    personalityTraits: ['Curious', 'Friendly', 'Food-motivated', 'Cheerful'],
    images: ['https://loremflickr.com/800/600/beagle?lock=17', 'https://loremflickr.com/400/300/beagle?lock=18', 'https://loremflickr.com/400/300/beagle?lock=19', 'https://loremflickr.com/400/300/beagle?lock=20'],
  },
  {
    id: '6',
    name: 'Shadow',
    type: 'Cat',
    breed: 'Bombay',
    age: '4 years',
    ageCategory: 'Adult',
    size: 'Medium',
    gender: 'Female',
    description: 'Shadow is a sleek and mysterious Bombay cat. She can be a bit shy at first, but once she warms up, she is a loving and devoted companion.',
    personalityTraits: ['Shy', 'Loving', 'Quiet', 'Graceful'],
    images: ['https://loremflickr.com/800/600/bombay,cat?lock=21', 'https://loremflickr.com/400/300/bombay,cat?lock=22', 'https://loremflickr.com/400/300/bombay,cat?lock=23', 'https://loremflickr.com/400/300/bombay,cat?lock=24'],
  },
  {
    id: '7',
    name: 'Daisy',
    type: 'Dog',
    breed: 'Poodle Mix',
    age: '5 years',
    ageCategory: 'Adult',
    size: 'Small',
    gender: 'Female',
    description: 'Daisy is a sweet and gentle Poodle mix who loves nothing more than to be a lap dog. She is hypoallergenic and would be perfect for a less active household.',
    personalityTraits: ['Gentle', 'Calm', 'Affectionate', 'Hypoallergenic'],
    images: ['https://loremflickr.com/800/600/poodle,dog?lock=25', 'https://loremflickr.com/400/300/poodle,dog?lock=26', 'https://loremflickr.com/400/300/poodle,dog?lock=27', 'https://loremflickr.com/400/300/poodle,dog?lock=28'],
  },
  {
    id: '8',
    name: 'Oliver',
    type: 'Cat',
    breed: 'British Shorthair',
    age: '8 years',
    ageCategory: 'Senior',
    size: 'Medium',
    gender: 'Male',
    description: 'Oliver is a distinguished gentleman looking for a peaceful retirement home. He enjoys long naps in sunbeams and gentle head scratches.',
    personalityTraits: ['Calm', 'Independent', 'Dignified', 'Sweet'],
    images: ['https://loremflickr.com/800/600/british,shorthair,cat?lock=29', 'https://loremflickr.com/400/300/british,shorthair,cat?lock=30', 'https://loremflickr.com/400/300/british,shorthair,cat?lock=31', 'https://loremflickr.com/400/300/british,shorthair,cat?lock=32'],
  }
];

export const featuredPets = allPets.slice(0, 4);
